# Generated by Django 4.2.1 on 2023-07-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kittyapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cat",
        ),
    ]
