# Generated by Django 4.2.1 on 2023-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kittyapp", "0002_delete_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoEstudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("tempo_contado", models.PositiveIntegerField()),
            ],
        ),
    ]
